on: [push, repository_dispatch]

env:
  GROUP_ID: com.octokat.app
  ARTIFACT_ID: install-octokat-app
  VERSION: 1.0-SNAPSHOT
  CLASS_NAME: InstallApp

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add pom.xml with dependency
        run: |
          cat > pom.xml << EOM
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>${{ env.GROUP_ID }}</groupId>
            <artifactId>${{ env.ARTIFACT_ID }}</artifactId>
            <version>${{ env.VERSION }}</version>
            <dependencies>
              <dependency>
                  <groupId>xyz.liblnd.prismarine</groupId>
                  <artifactId>prismarine-api</artifactId>
                  <version>1.16.2-R0.1-SNAPSHOT</version>
                  <scope>provided</scope>
                  <classifier>shaded</classifier>
              </dependency>
            </dependencies>
            <repositories>
              <repository>
                  <id>github</id>
                  <url>https://maven.pkg.github.com/libertyland/prismarine/</url>
              </repository>
            </repositories>
          </project>
          EOM
      - name: Add ${{ env.CLASS_NAME }}.java file
        run: |
          SOURCE_PATH=src/main/java/$(echo ${{ env.GROUP_ID }} | tr . /)
          mkdir -p $SOURCE_PATH
          cat <<- END > $SOURCE_PATH/${{ env.CLASS_NAME }}.java
          package ${{ env.GROUP_ID }};
          public class ${{ env.CLASS_NAME }}
          {
              public static void main( String[] args )
              {
              }
          }
          END
      - name: Install packages
        run: mvn install --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Exec package
        run: mvn exec:java -D exec.mainClass=${{ env.GROUP_ID }}.${{ env.CLASS_NAME }} --no-transfer-progress
